/*
DROP SEQUENCE SQ_AM_ART_ESTADO;
DROP SEQUENCE SQ_AM_ART_CIDADE;
DROP SEQUENCE SQ_AM_ART_BAIRRO;
DROP SEQUENCE SQ_AM_ART_TIPO_LOG;
DROP SEQUENCE SQ_AM_ART_TIPO_FONE;
DROP SEQUENCE SQ_AM_ART_TELEFONE;
DROP SEQUENCE SQ_AM_ART_PESSOA;
DROP SEQUENCE SQ_AM_ART_PESSOA_ENDE;
DROP SEQUENCE SQ_AM_ART_TIPO_CAUSA;
DROP SEQUENCE SQ_AM_ART_TIPO_DESPESA;
DROP SEQUENCE SQ_AM_ART_TIPO_TAREFA;
DROP SEQUENCE SQ_AM_ART_LANCA_HONORARIO;
DROP SEQUENCE SQ_AM_ART_HIST_TAXA;
DROP SEQUENCE SQ_AM_ART_PROCESSO;
DROP SEQUENCE SQ_AM_ART_LANCA_DESPESA;
*/


-- TABELA ESTADO
CREATE SEQUENCE SQ_AM_ART_ESTADO
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;

-- TABELA CIDADE
CREATE SEQUENCE SQ_AM_ART_CIDADE
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

-- TABELA BAIRRO
CREATE SEQUENCE SQ_AM_ART_BAIRRO
INCREMENT BY 1
START WITH 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

-- TABELA TIPO_LOG
CREATE SEQUENCE SQ_AM_ART_TIPO_LOG
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;

-- TABELA TIPO_FONE
CREATE SEQUENCE SQ_AM_ART_TIPO_FONE
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;

-- TABELA TELEFONE
CREATE SEQUENCE SQ_AM_ART_TELEFONE
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

-- TABELA PESSOA
CREATE SEQUENCE SQ_AM_ART_PESSOA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

-- TABELA PESSOA_ENDE
CREATE SEQUENCE SQ_AM_ART_PESSOA_ENDE
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
NOCACHE
NOCYCLE;

--TABELA TIPO_CAUSA
CREATE SEQUENCE SQ_AM_ART_TIPO_CAUSA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

-- TABELA TIPO_DESPESA
CREATE SEQUENCE SQ_AM_ART_TIPO_DESPESA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

--TABELA TIPO_TAREFA
CREATE SEQUENCE SQ_AM_ART_TIPO_TAREFA
INCREMENT BY 1
START WITH 1
MAXVALUE 999
NOCACHE
NOCYCLE;

--TABELA LANCA_HONORARIO
CREATE SEQUENCE SQ_AM_ART_LANCA_HONORARIO
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
NOCACHE
NOCYCLE;

-- TABELA HIST_TAXA
CREATE SEQUENCE SQ_AM_ART_HIST_TAXA
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

-- TABELA PROCESSO
CREATE SEQUENCE SQ_AM_ART_PROCESSO
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
NOCACHE
NOCYCLE;

-- TABELA LANCA_DESPESA
CREATE SEQUENCE SQ_AM_ART_LANCA_DESPESA
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
NOCACHE
NOCYCLE;
